source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'duktape'
gem 'tzinfo-data'
gem 'will_paginate',     '~> 4.0'
gem 'hubssolib',         '~> 2.0', :require => 'hub_sso_lib'
gem 'invisible_captcha', '~> 2.3'
gem 'rails-observers'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7'

# Use PostgresSQL as the database for Active Record
gem 'pg', '~> 1.5.8'

# # Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"

# Use SCSS for stylesheets
gem 'sass-rails', '~> 6.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use CoffeeScript for .coffee assets and views

gem 'coffee-rails', '~> 4.2'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'

  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'webdrivers'
end
