source 'https://rubygems.org'

gem 'rails', '~> 8.0'

# Use PostgreSQL
#
gem 'pg', '~> 1.5'

# Use the Puma web server [https://github.com/puma/puma]
#
gem 'puma', '~> 6.0'

# For Windows or esoteric Unix/Linux-like distributions.
#
gem 'tzinfo-data'

# Simple asset management
#
gem 'propshaft', '~> 1.1'

# Easy pagination [https://rubygems.org/gems/pagy]
#
gem 'pagy', '~> 9.3'

# Invisible sign-in protection against bots (marginally effective) [https://rubygems.org/gems/invisible_captcha]
#
gem 'invisible_captcha', '~> 2.3'

# Use Hub for authentication, obviously ;-) [https://github.com/pond/hubssolib]
#
gem 'hubssolib', '~> 3.0', require: 'hub_sso_lib'

# # Monitoring and alerting [http://rubygems.org/gems/newrelic_rpm]
# #
# gem 'newrelic_rpm'

# Monitoring and alerting [http://sentry.io]
#
# * https://rubygems.org/gems/stackprof
# * https://rubygems.org/gems/sentry-ruby
# * https://rubygems.org/gems/sentry-rails
#
gem 'stackprof'
gem 'sentry-ruby'
gem 'sentry-rails'

group :development, :test do

  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  #
  gem 'debug', platforms: %i[ mri windows ]

end

group :development do

  # Use console on exceptions pages [https://github.com/rails/web-console]
  #
  gem 'web-console'

  # Be able to run 'bin/dev'
  #
  gem 'foreman'

  # E-mail inspection.
  #
  gem 'mailcatcher'

end

group :test do

  # Adds support for Capybara system testing and selenium driver
  #
  gem 'capybara', '~> 3.4'
  gem 'selenium-webdriver'

  # Easy installation and use of chromedriver to run system tests with Chrome
  #
  gem 'webdrivers'

end
